import React, { useEffect, useState } from 'react';

export default function App() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState('');
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [processing, setProcessing] = useState(false);

  useEffect(() => {
    if (!file) {
      setPreview('');
      return;
    }
    const url = URL.createObjectURL(file);
    setPreview(url);
    return () => URL.revokeObjectURL(url);
  }, [file]);

  function selectImage(event) {
    const selected = event.target.files[0];
    setResult(null);
    setError('');
    setFile(null);
    if (!selected) return;
    if (!/\.(jpe?g|png)$/i.test(selected.name)) {
      setError('Please select a JPG or PNG image.');
      event.target.value = '';
      return;
    }
    if (selected.size > 10 * 1024 * 1024) {
      setError('The image must be 10 MB or smaller.');
      event.target.value = '';
      return;
    }
    setFile(selected);
  }

  async function processImage(event) {
    event.preventDefault();
    if (!file || processing) return;
    setProcessing(true);
    setResult(null);
    setError('');
    const form = new FormData();
    form.append('file', file);
    try {
      const response = await fetch('/api/process', {
        method: 'POST',
        body: form,
        signal: AbortSignal.timeout(30000),
      });
      const data = await response.json().catch(() => null);
      if (!response.ok) {
        throw new Error(typeof data?.detail === 'string'
          ? data.detail : 'Processing failed. Check that the FastAPI backend is running.');
      }
      if (!data) throw new Error('The backend returned an invalid response.');
      setResult(data);
    } catch (err) {
      setError(err.name === 'TimeoutError'
        ? 'The request timed out. Please check the backend and try again.'
        : err instanceof TypeError
          ? 'Cannot reach the backend. Start FastAPI and try again.'
          : err.message);
    } finally {
      setProcessing(false);
    }
  }

  return (
    <main>
      <header>
        <p className="eyebrow">FINAL YEAR PROJECT · MID-DEFENSE PROTOTYPE</p>
        <h1>AI-Based Nepali Vehicle Number Plate Detection and Recognition System</h1>
        <p className="intro">Upload a vehicle image to validate it and explore real OpenCV grayscale preprocessing.</p>
      </header>

      <section className="pipeline" aria-label="Development status">
        <span className="ready">Image upload &amp; preprocessing: Available</span>
        <span>YOLO detection: Pending model training</span>
        <span>OCR recognition: Pending integration</span>
      </section>

      <section className="card">
        <h2>Upload a vehicle image</h2>
        <form onSubmit={processImage}>
          <label htmlFor="vehicle-image">Choose image</label>
          <input id="vehicle-image" type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png"
            onChange={selectImage} disabled={processing} aria-describedby="file-help" />
          <p id="file-help" className="muted">JPG or PNG · Up to 10 MB and 20 megapixels</p>
          <button type="submit" disabled={!file || processing}>
            {processing ? 'Processing image…' : 'Upload / Process Image'}
          </button>
        </form>
        {error && <p className="error" role="alert">{error}</p>}
        <p className="status" role="status">
          {processing ? 'Uploading and preparing the grayscale preview…'
            : result ? 'Image validated and processed successfully.' : ''}
        </p>
        {result && (
          <dl className="metadata">
            <div><dt>Original width</dt><dd>{result.width.toLocaleString()} px</dd></div>
            <div><dt>Original height</dt><dd>{result.height.toLocaleString()} px</dd></div>
            <div><dt>Format</dt><dd>{result.format}</dd></div>
          </dl>
        )}
      </section>

      <section className="previews" aria-label="Image previews">
        <article className="card">
          <h2>Selected image</h2>
          {preview ? <img src={preview} alt="Selected vehicle" onError={() => {
            setPreview('');
            setError('This file cannot be previewed. Select a valid JPG or PNG image.');
            setFile(null);
          }} /> : <div className="placeholder">Your selected image will appear here.</div>}
        </article>
        <article className="card">
          <h2>OpenCV grayscale</h2>
          {result ? <img src={result.grayscale_image} alt="Grayscale version generated by OpenCV" />
            : <div className="placeholder">Process an image to see the grayscale output.</div>}
          <p className="muted">Full-image preprocessing. Preview resized to at most 1,200 pixels on its longest side.</p>
        </article>
      </section>
      <footer>This prototype demonstrates image upload and preprocessing. Automatic plate detection, cropping, and character recognition are pending. Uploaded images are not saved by this application.</footer>
    </main>
  );
}
